name: Build and Test

on:  [ push, pull_request ]

env:
  external_version: 1.66.0
  external_name: boost_1_66_0
  external_path: ~/Boost

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [ python, python3 ]
        cxx: [ g++, clang ]
        std: [ c++98, c++11]

    steps:
    - uses: actions/checkout@v2

    - name: Cache Boost Version
      id: cache-boost
      uses: actions/cache@v2
      env:
        cache-name: external-boost

      with:
        path: ${{ env.external_path }}
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.external_version}}

    - name: Boost Prerequisites
      if: steps.cache-boost.outputs.cache-hit != 'true'
      run: |
        wget https://sourceforge.net/projects/boost/files/boost/${{ env.external_version }}/${{ env.external_name}}.tar.gz/download
        tar xf download
        pushd ${{ env.external_name }}
        ./bootstrap.sh
        ./b2 tools/bcp
        mkdir -p ${{ env.external_path }}
        # Install Boost.Python prerequisites, but not Boost.Python itself.
        dist/bin/bcp python tools/boostbook tools/quickbook ${{ env.external_path }} &> /dev/null
        popd

    - name: Clear Boost Python
      run: rm -rf ${{ env.external_path }}/boost/python

    - name: OS Prerequisites
      run: |
      sudo apt update
      sudo apt install \
        gcc \
        g++ \
        clang \
        pypy3-dev
        python3-pip \
        python3-numpy \
        python3-dev \
        python-numpy \
        python-dev \
        libboost-all-dev \
        xsltproc \
        docbook-xsl \
        python-sphinx \
        python-docutils

    - name: Faber Setup
      run: |
        python3 -m pip install setuptools
        python3 -m pip install Faber
        sed -e "s/\$PYTHON/$PYTHON/g" .ci/faber > ~/.faber

    - name: Test
      run: |
        $PYTHON --version
        faber -h
        ls -l ${{ env.external_path }}
        
        faber \
          --with-boost-include=${{ env.external_path }} \
          --builddir=build test.report \
          cxx.name=${{ matrix.cxx }} \
          cxxflags=-std=${{ matrix.std }} \
          -j8
